# Generated by Django 6.0 on 2025-12-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('medium', models.URLField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('programming', models.TextField(blank=True, null=True)),
                ('communication', models.TextField(blank=True, null=True)),
                ('tools', models.TextField(blank=True, null=True)),
                ('projects', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
