# Generated by Django 6.0 on 2025-12-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
