# Generated by Django 6.0 on 2025-12-17 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_education_experience_projects_siteprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('Programming', 'programming'), ('AI, ML and NLP', 'Ai, Ml and Nlp'), ('Data Engineering and Visualization', 'data engineering and visualization'), ('Cloud and Optimization', 'cloud and optimization'), ('SDLC and Devops', 'sdlc and devops')], max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.siteprofile')),
            ],
        ),
    ]
