# Generated by Django 6.0 on 2025-12-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='category',
            field=models.CharField(choices=[('Programming', 'programming'), ('AI, ML and NLP', 'Ai, Ml and Nlp'), ('Data Engineering and Visualization', 'data engineering and visualization'), ('SDLC, Cloud and Devops', 'sdlc cloud and devops')], max_length=100),
        ),
    ]
