# Generated by Django 6.0 on 2025-12-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_skills_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
