# Generated by Django 6.0 on 2025-12-20 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_siteprofile_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='proj_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='resume_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='portfolio.siteprofile')),
            ],
        ),
    ]
