# Generated by Django 6.0 on 2025-12-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_projects_proj_image_url_siteprofile_resume_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socials',
            name='icon_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
