# Generated by Django 6.0 on 2025-12-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_socials_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='proj_image_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
