# Generated by Django 6.0 on 2025-12-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_projects_proj_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='resume_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
